// <auto-generated />
namespace Bazar_Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class agregamosprecioystock : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(agregamosprecioystock));
        
        string IMigrationMetadata.Id
        {
            get { return "201906022247143_agregamos precio y stock"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
